// Generated by CoffeeScript 1.9.3
var RE_CHARSET, RE_TITLE, convertToUtf8, jconv, ogs, request;

request = require("request");

jconv = require('jconv');

ogs = require('open-graph-scraper');

RE_TITLE = /<title>(.+?)<\/title>/i;

RE_CHARSET = /charset=([^<>"']+)/i;

convertToUtf8 = function(response, str) {
  var charset, cnt_type;
  charset = null;
  charset = null;
  cnt_type = response.headers['content-type'];
  if (cnt_type) {
    charset = cnt_type.match(RE_CHARSET);
  }
  if (str && charset === null) {
    charset = str.toString("UTF8").match(RE_CHARSET);
  }
  if (str && charset) {
    charset = charset[1].toUpperCase();
    try {
      str = jconv.convert(str, charset, "UTF8");
    } catch (_error) {

    }
  }
  str = str.toString("UTF-8");
  return str;
};

exports.parse = function(url, callback, timeout) {
  var args;
  timeout = timeout || 5000;
  args = {
    "url": url,
    "timeout": timeout
  };
  args.encoding = null;
  return request(args, function(error, response, body) {
    var title;
    if (error || response.statusCode !== 200) {
      return callback({
        'error': error
      });
    } else {
      body = convertToUtf8(response, body);
      title = body.match(RE_TITLE);
      if (title) {
        title = title[1];
      } else {
        title = url;
      }
      return ogs({
        "url": url,
        "timeout": timeout
      }, (function(_this) {
        return function(err, results) {
          var data, return_data;
          return_data = {
            'title': title,
            'favicon': 'https://www.google.com/s2/favicons?domain=' + url
          };
          if (results.success) {
            data = results.data;
            if (data) {
              if (data.ogImage) {
                return_data.thumbnail = data.ogImage;
              }
              if (data.ogDescription) {
                return_data.description = data.ogDescription;
              }
            }
          }
          return callback(return_data);
        };
      })(this));
    }
  });
};
