// Generated by CoffeeScript 1.7.1
var Iconv, RE_CHARSET, RE_TITLE, convertToUtf8, request;

request = require("request");

Iconv = require('iconv').Iconv;

RE_TITLE = /<title>(.+?)<\/title>/i;

RE_CHARSET = /charset=(.+)/i;

convertToUtf8 = function(response, str) {
  var charset, cnt_type, iconv;
  cnt_type = response.headers['content-type'];
  if (cnt_type) {
    charset = cnt_type.match(RE_CHARSET);
    if (charset) {
      charset = charset[1].toUpperCase();
      iconv = new Iconv(charset, 'UTF-8//TRANSLIT//IGNORE');
      str = iconv.convert(str);
    }
  }
  str = str.toString("UTF-8");
  return str;
};

exports.parse = function(url, callback, timeout) {
  var args;
  timeout = timeout || 5000;
  args = {
    "url": url,
    "timeout": timeout
  };
  args.encoding = null;
  return request(args, function(error, response, body) {
    var title;
    if (error || response.statusCode !== 200) {
      return callback({
        'error': error
      });
    } else {
      title = convertToUtf8(response, body).match(RE_TITLE);
      if (title) {
        title = title[1];
      } else {
        title = url;
      }
      return callback({
        'title': title,
        'favicon': 'https://www.google.com/s2/favicons?domain=' + url
      });
    }
  });
};
