// Generated by CoffeeScript 1.7.1
var RE_TITLE, jconv, request;

request = require("request");

jconv = require("jconv");

RE_TITLE = /<title>(.+?)<\/title>/i;

exports.parse = function(url, callback, timeout) {
  var args;
  timeout = timeout || 5000;
  args = {
    "url": url,
    "timeout": timeout
  };
  args.encoding = null;
  return request(args, function(error, response, body) {
    var cnt_type, e, title;
    if (error || response.statusCode !== 200) {
      return callback({
        'error': error
      });
    } else {
      title = body.toString("UTF-8").match(RE_TITLE);
      if (title) {
        title = title[1];
        cnt_type = response.headers['content-type'];
        if (cnt_type) {
          if (cnt_type.toLowerCase().indexOf('euc-jp') !== -1) {
            try {
              title = jconv.convert(title.toString("binary"), 'EUCJP', 'UTF-8').toString();
            } catch (_error) {
              e = _error;
              title = url;
            }
          }
        }
      } else {
        title = url;
      }
      return callback({
        'title': title,
        'favicon': 'https://www.google.com/s2/favicons?domain=' + url
      });
    }
  });
};
